#
# helix configuration for local development
#
version: 1

definitions:
  defaults:
    - &defaultRepo "ssh://git@github.com/alexkli/helix-mytestproject.git"

strains:
  - name: default
    code: *defaultRepo
    content: *defaultRepo
    static: *defaultRepo
